//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrepeDuChef.Maui.Resources.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Traduction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Traduction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrepeDuChef.Maui.Resources.languages.Traduction", typeof(Traduction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a chef.
        /// </summary>
        internal static string AddAChef {
            get {
                return ResourceManager.GetString("AddAChef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chefs in attendance:.
        /// </summary>
        internal static string ChefsPresent {
            get {
                return ResourceManager.GetString("ChefsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the chef&apos;s crepe.
        /// </summary>
        internal static string CrepeDuChef_title {
            get {
                return ResourceManager.GetString("CrepeDuChef_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first and last name..
        /// </summary>
        internal static string EnterFirstAndLastName {
            get {
                return ResourceManager.GetString("EnterFirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information has been updated.
        /// </summary>
        internal static string InformationUpdated {
            get {
                return ResourceManager.GetString("InformationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user form data..
        /// </summary>
        internal static string InvalidUserFormData {
            get {
                return ResourceManager.GetString("InvalidUserFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add at least 1 chef.
        /// </summary>
        internal static string NeedAtLeastOneChef {
            get {
                return ResourceManager.GetString("NeedAtLeastOneChef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chef is listed.
        /// </summary>
        internal static string NoChefInDB {
            get {
                return ResourceManager.GetString("NoChefInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chef selected.
        /// </summary>
        internal static string NoChefSelected {
            get {
                return ResourceManager.GetString("NoChefSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to select a chief..
        /// </summary>
        internal static string NoChefSelectionExceptionMessage {
            get {
                return ResourceManager.GetString("NoChefSelectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoName.
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sessions saved..
        /// </summary>
        internal static string NoSessionInDb {
            get {
                return ResourceManager.GetString("NoSessionInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Canceled.
        /// </summary>
        internal static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one chef..
        /// </summary>
        internal static string SelectAtLeastOneChef {
            get {
                return ResourceManager.GetString("SelectAtLeastOneChef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all sessions.
        /// </summary>
        internal static string ShowAllSession {
            get {
                return ResourceManager.GetString("ShowAllSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only current session.
        /// </summary>
        internal static string ShowOnlyCurrentSession {
            get {
                return ResourceManager.GetString("ShowOnlyCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Chef is.
        /// </summary>
        internal static string Today_s_Chef {
            get {
                return ResourceManager.GetString("Today_s_Chef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update a Chef.
        /// </summary>
        internal static string UpdateAChef {
            get {
                return ResourceManager.GetString("UpdateAChef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update first and/or last name..
        /// </summary>
        internal static string UpdateFirstAndOrLastName {
            get {
                return ResourceManager.GetString("UpdateFirstAndOrLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated.
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any users who aren&apos;t here?.
        /// </summary>
        internal static string UsersAway {
            get {
                return ResourceManager.GetString("UsersAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        internal static string UserSetting {
            get {
                return ResourceManager.GetString("UserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is the Chef ?.
        /// </summary>
        internal static string WhoIsTheChef {
            get {
                return ResourceManager.GetString("WhoIsTheChef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter first and last name..
        /// </summary>
        internal static string YouMustEnterFirstAndLastName {
            get {
                return ResourceManager.GetString("YouMustEnterFirstAndLastName", resourceCulture);
            }
        }
    }
}
