<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrepeDuChef.Domain\CrepeDuChef.Domain.csproj" />
    <ProjectReference Include="..\CrepeDuChef.Localization\CrepeDuChef.Localization.csproj" />
  </ItemGroup>

</Project>
