<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrepeDuChef.Domain\CrepeDuChef.Domain.csproj" />
    <ProjectReference Include="..\CrepeDuChef.Localization\CrepeDuChef.Localization.csproj" />
  </ItemGroup>

</Project>
